# Generated by Django 6.0.3 on 2026-03-14 17:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('professor', 'Professor'), ('responsavel', 'Responsável'), ('Cliente', 'Cliente'), ('admin', 'Admin Tenant')], default='admin', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('acesso_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('acesso_token_expira_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_exibicao', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('especialidade', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PacoteAulas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=500)),
                ('qtd_aulas_total', models.PositiveIntegerField()),
                ('qtd_aulas_usadas', models.PositiveIntegerField(default=0)),
                ('aulas_restantes', models.IntegerField(editable=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.cliente')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('relacao_cliente', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=500)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('parcialmente_paga', 'Parcialmente Paga'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='aberta', max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='attend.cliente')),
                ('pacote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attend.pacoteaulas')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attend.responsavel')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attend.responsavel'),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('nome_fantasia', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('plano', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('limite_clientes', models.PositiveIntegerField(default=10)),
                ('data_inicio_plano', models.DateField()),
                ('data_fim_plano', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug', 'ativo'], name='attend_tena_slug_59d776_idx')],
            },
        ),
        migrations.AddField(
            model_name='responsavel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.tenant'),
        ),
        migrations.CreateModel(
            name='ProfessorTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.professor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='tenants',
            field=models.ManyToManyField(related_name='professores', to='attend.tenant'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metodo', models.CharField(choices=[('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto'), ('dinheiro', 'Dinheiro')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('falhou', 'Falhou'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('gateway', models.CharField(blank=True, max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100)),
                ('pix_qr_code', models.TextField(blank=True)),
                ('pix_copia_cola', models.TextField(blank=True)),
                ('webhook_recebido', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='attend.fatura')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='pacoteaulas',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.tenant'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.tenant'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inicio', models.DateField()),
                ('preferred_instructor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancell  ed')], default='ativo', max_length=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='attend.cliente')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.pacoteaulas')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='attend.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.tenant'),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('remarcada', 'Remarcada'), ('solicitada_remarcacao', 'Solicitada Remarcação')], default='agendada', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origem_remarcacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attend.aula')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='attend.cliente')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='attend.pacoteaulas')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.professor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attend.tenant'),
        ),
        migrations.AddIndex(
            model_name='responsavel',
            index=models.Index(fields=['tenant'], name='attend_resp_tenant__8bd2e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='professortenant',
            unique_together={('tenant', 'professor')},
        ),
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['ativo'], name='attend_prof_ativo_19bb5d_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['tenant', 'fatura'], name='attend_paga_tenant__9c2e53_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['tenant', 'status'], name='attend_paga_tenant__402734_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['tenant', 'gateway_transaction_id'], name='attend_paga_tenant__edd4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='pacoteaulas',
            index=models.Index(fields=['tenant', 'cliente'], name='attend_paco_tenant__bf4ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='pacoteaulas',
            index=models.Index(fields=['tenant', 'status'], name='attend_paco_tenant__5cf8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='pacoteaulas',
            index=models.Index(fields=['tenant', 'data_fim'], name='attend_paco_tenant__81c2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['tenant', 'cliente'], name='attend_fatu_tenant__e6ff63_idx'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['tenant', 'status'], name='attend_fatu_tenant__3f673a_idx'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['tenant', 'data_vencimento'], name='attend_fatu_tenant__a14019_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['tenant', 'nome'], name='attend_clie_tenant__9a8176_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['tenant', 'responsavel'], name='attend_clie_tenant__a8ab72_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['tenant', 'data_hora_inicio'], name='attend_aula_tenant__569004_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['tenant', 'cliente', 'status'], name='attend_aula_tenant__6cb901_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['tenant', 'pacote'], name='attend_aula_tenant__84ad1e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'email'], name='attend_user_tenant__cbae79_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'tipo_usuario'], name='attend_user_tenant__a9a187_idx'),
        ),
    ]
