# Generated by Django 6.0.3 on 2026-03-26 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacoteSessoes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('qtd_sessoes', models.PositiveIntegerField()),
                ('valor_por_sessao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_parcelas', models.PositiveIntegerField(default=1)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_pagamento', models.PositiveSmallIntegerField()),
                ('qtd_sessoes_usadas', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_exibicao', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('especialidade', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('remarcada', 'Remarcada'), ('solicitada_remarcacao', 'Solicitada Remarcação')], default='agendada', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='aula',
            name='attend_aula_tenant__569004_idx',
        ),
        migrations.RemoveIndex(
            model_name='aula',
            name='attend_aula_tenant__6cb901_idx',
        ),
        migrations.RemoveIndex(
            model_name='aula',
            name='attend_aula_tenant__84ad1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='pacoteaulas',
            name='attend_paco_tenant__bf4ee6_idx',
        ),
        migrations.RemoveIndex(
            model_name='pacoteaulas',
            name='attend_paco_tenant__5cf8ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='pacoteaulas',
            name='attend_paco_tenant__81c2ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='professor',
            name='attend_prof_ativo_19bb5d_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('Profissional', 'Profissional'), ('responsavel', 'Responsável'), ('Cliente', 'Cliente'), ('admin', 'Admin Tenant')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='pacotesessoes',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes', to='attend.cliente'),
        ),
        migrations.AddField(
            model_name='pacotesessoes',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes', to='attend.tenant'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pacote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.pacotesessoes'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='pacote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attend.pacotesessoes'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='tenants',
            field=models.ManyToManyField(related_name='profissionais', to='attend.tenant'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profissional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pacotesessoes',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes', to='attend.profissional'),
        ),
        migrations.AddField(
            model_name='profissionaltenant',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.profissional'),
        ),
        migrations.AddField(
            model_name='profissionaltenant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.tenant'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='attend.cliente'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='origem_remarcacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attend.sessao'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='pacote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='attend.pacotesessoes'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.profissional'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.tenant'),
        ),
        migrations.RemoveField(
            model_name='aula',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='origem_remarcacao',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='pacote',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='pacoteaulas',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pacoteaulas',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='pacoteaulas',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='tenants',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfessorTenant',
        ),
        migrations.AddIndex(
            model_name='profissional',
            index=models.Index(fields=['ativo'], name='attend_prof_ativo_f76aea_idx'),
        ),
        migrations.AddIndex(
            model_name='pacotesessoes',
            index=models.Index(fields=['tenant', 'cliente'], name='attend_paco_tenant__393038_idx'),
        ),
        migrations.AddIndex(
            model_name='pacotesessoes',
            index=models.Index(fields=['tenant', 'status'], name='attend_paco_tenant__35931d_idx'),
        ),
        migrations.AddIndex(
            model_name='pacotesessoes',
            index=models.Index(fields=['tenant', 'data_fim'], name='attend_paco_tenant__7645d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profissionaltenant',
            unique_together={('tenant', 'profissional')},
        ),
        migrations.AddIndex(
            model_name='sessao',
            index=models.Index(fields=['tenant', 'data_hora_inicio'], name='attend_sess_tenant__16cc66_idx'),
        ),
        migrations.AddIndex(
            model_name='sessao',
            index=models.Index(fields=['tenant', 'cliente', 'status'], name='attend_sess_tenant__7c9d50_idx'),
        ),
        migrations.AddIndex(
            model_name='sessao',
            index=models.Index(fields=['tenant', 'pacote'], name='attend_sess_tenant__079149_idx'),
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
        migrations.DeleteModel(
            name='PacoteAulas',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
