# Generated by Django 6.0.3 on 2026-03-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0002_pacotesessoes_profissional_profissionaltenant_sessao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacotesessoes',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
