# Generated by Django 6.0.3 on 2026-03-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0004_cliente_cpf_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
