# Generated by Django 6.0.3 on 2026-03-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='foto',
        ),
    ]
