# Generated by Django 6.0.3 on 2026-03-30 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0007_rename_avatar_profile_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('max_profissionais', models.PositiveIntegerField(default=1)),
                ('permite_multiplos_profissionais', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('contrato_inicio', models.DateField(blank=True, null=True)),
                ('contrato_fim', models.DateField(blank=True, null=True)),
                ('acesso_ativo', models.BooleanField(default=True)),
                ('cadastro_finalizado', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_portal', to='attend.tenant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('used', 'Usado'), ('expired', 'Expirado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('portal_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='attend.portalcliente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='portalcliente',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='uniq_cliente_email_por_tenant'),
        ),
    ]
