# Generated by Django 6.0.3 on 2026-04-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0009_add_portalcliente_access_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalcliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portalcliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
