# Generated by Django 6.0.3 on 2026-04-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0010_alter_portalcliente_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacotesessoes',
            name='parcelas_preview',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pacotesessoes',
            name='plano_tipo',
            field=models.CharField(choices=[('basico', 'Básico'), ('pro', 'Pro'), ('premium', 'Premium')], default='basico', max_length=20),
        ),
        migrations.AddField(
            model_name='pacotesessoes',
            name='sessoes_preview',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='pacotesessoes',
            name='qtd_sessoes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plano',
            field=models.CharField(choices=[('basico', 'Básico'), ('pro', 'Pro'), ('premium', 'Premium')], default='basico', max_length=20),
        ),
    ]
