# Generated by Django 6.0.3 on 2026-04-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0011_pacotesessoes_parcelas_preview_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profissional',
            name='attend_prof_ativo_f76aea_idx',
        ),
        migrations.AlterUniqueTogether(
            name='profissionaltenant',
            unique_together={('profissional', 'tenant')},
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='ativo',
        ),
    ]
