# Generated by Django 6.0.3 on 2026-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0012_remove_profissional_attend_prof_ativo_f76aea_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais/'),
        ),
    ]
