# Generated by Django 6.0.3 on 2026-05-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0013_profissional_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
